name: ClusterFuzzLite coverage

concurrency:
  group: clusterfuzzlite-coverage
  cancel-in-progress: true

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Coverage:
    if: ${{ github.repository == 'tfw-org/tfw' }}
    runs-on: ubuntu-latest

    steps:
      - name: Build Fuzzers
        id: build
        uses: ./.github/actions/cflite-build-fuzzers
        with:
          language: jvm
          sanitizer: coverage

      - name: Generate Coverage Report
        id: run
        uses: ./.github/actions/cflite-run-fuzzers
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 600
          mode: coverage
          sanitizer: coverage
          language: jvm
          storage-repo: https://${{ secrets.TFW_FUZZING_TOKEN }}@github.com/tfw-org/tfw-fuzzing.git
          storage-repo-branch: main
          storage-repo-branch-coverage: gh-pages
