name: ClusterFuzzLite PR fuzzing

on:
  pull_request:
    paths:
      - 'src/main/java/tfw/immutable/**'
      - 'src/fuzz/**'
      - '.clusterfuzzlite/**'
      - '.github/workflows/cflite_pr.yml'
      - 'pom.xml'

permissions: read-all

jobs:
  PR:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        sanitizer:
          - address

    steps:
      - name: Build Fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@v1
        with:
          language: jvm
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sanitizer: ${{ matrix.sanitizer }}

      - name: Run Fuzzers
        id: run
        uses: google/clusterfuzzlite/actions/run_fuzzers@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 300
          mode: code-change
          sanitizer: ${{ matrix.sanitizer }}
          output-sarif: true
