name: Release to Maven Central

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Configure java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          java-version: 21
          distribution: corretto
          server-id: central
          server-username: MVN_USERNAME
          server-password: MVN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Get Maven artifact information
        id: maven
        run: |
          echo "artifactId=$(mvn -ntp -q help:evaluate -Dexpression=project.artifactId -DforceStdout)" >> "$GITHUB_OUTPUT"
          echo "version=$(mvn -ntp -q help:evaluate -Dexpression=project.version -DforceStdout)" >> "$GITHUB_OUTPUT"

      - name: Publish package
        run: mvn -ntp -B deploy -P release
        env:
          MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
          MVN_PASSWORD: ${{ secrets.MVN_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Upload Artifacts and Signatures to GitHub Release
        run: |
          gh release upload "${{ github.event.release.tag_name }}" \
            "target/${{ steps.maven.outputs.artifactId }}-${{ steps.maven.outputs.version }}.jar" \
            "target/${{ steps.maven.outputs.artifactId }}-${{ steps.maven.outputs.version }}.jar.asc" \
            "target/${{ steps.maven.outputs.artifactId }}-${{ steps.maven.outputs.version }}-sources.jar" \
            "target/${{ steps.maven.outputs.artifactId }}-${{ steps.maven.outputs.version }}-sources.jar.asc" \
            "target/${{ steps.maven.outputs.artifactId }}-${{ steps.maven.outputs.version }}-javadoc.jar" \
            "target/${{ steps.maven.outputs.artifactId }}-${{ steps.maven.outputs.version }}-javadoc.jar.asc"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}